### PR TITLE
Added problem 54. SpiralMatrix.java

### PR DESCRIPTION
**Pull request by ana2407**
Added Leetcode problem 54. SpiralMatrix.java

### CODE REVIEW

**Comment by piyushsharma220699** [comment]
Please read the NOTE FOR CONTRIBUTORS.md file, add the link to code, sample input/output along with required comments and Time/Space Complexity :)

**Comment by ana2407** [comment]
Added question link with sample input/output and time,space complexity.

**Comment by piyushsharma220699** [comment]
Please create the issue first, get this assigned to you and then commit it! (Just read the NOTE FOR CONTRIBUTORS.md file once). I'll accept it for sure 🥇

**Comment by piyushsharma220699** [comment]
@ana2407 For now, I need to close this!

**Pull request closed without merging**
